version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      FLASK_ENV: development  # o production a seconda dell'ambiente
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
